Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:Ot123456@tcp(127.0.0.1:3306)/shopping?charset=utf8mb4&parseTime=True&loc=Local"
  DatabaseName: "location"
  Username: "root"
  Password: "Ot123456"

NewRelicSettings:
  LicenseKey: "YOUR_LICENSE_KEY"
  AppName: "YOUR_APP_NAME"

JwtSettings:
  SecretKey: "OGUZHANTASIMAZSECRETKEY"